### ISSUE TITLE
Miss aligned printing

### ISSUE THREAD

**Issue by PrietoM** [data-forge-notebook/wiki#10]
Is there a way we can make the print out look like in the console (See picture)
![danfojs](https://user-images.githubusercontent.com/802861/107261965-38789100-69fd-11eb-8fef-fe9df5e66e13.png)

Tried using the various display. functions to no avail.

The only way to make it look good is to make the notebook window width really thin.
Thanks!!

FYI, you will have to install the npm library @babel/runtime to make danfojs-node work properly

**Comment by ashleydavis** [comment]
Thanks for your feedback. I'll look into it.

**Comment by ashleydavis** [comment]
I'm working on a proper solution for multi-line text, but in the meantime here's a workaround:

![image](https://user-images.githubusercontent.com/625126/107868817-8436a900-6edb-11eb-87e0-75ab2f679a01.png)

**Comment by ashleydavis** [comment]
I've fixed this in Data-Forge Notebook v1.10.4, this version will be released within 2 weeks.
