### ISSUE TITLE
SHIFT + / opens the keyboard shortcuts menu

### ISSUE THREAD

**Issue by cwouter** [data-forge-notebook/wiki#11]
This is quite annoying in my case since it's the same key combination to write a forward slash. 
I am working on a mac with an AZERTY keyboard layout.

**Comment by ashleydavis** [comment]
Would it be ok if it was Ctrl/Cmd + Shift + / ?

**Comment by cwouter** [comment]
Yes much better! thx

**Comment by ashleydavis** [comment]
Cool, sorry for the inconvenience. I'll get a new version through in the next 2 weeks.

**Comment by cwouter** [comment]
No problem at all! Thanks for the quick support ;-)

**Comment by ashleydavis** [comment]
Sorry been a bit crazy, hoping to look at this soon.

**Comment by ashleydavis** [comment]
I've fixed this issue. I realised the the hotkey was always supposed to be ctrl/command + shift + forward slash, but there was a bug that mean it was triggered only by shift + forward slash.

Fix coming soon in version 1.10.5.

Thanks for reporting the issue.
