### ISSUE TITLE
Close button "X" in the keyboard shortcuts dialog doesn't work

### ISSUE THREAD

**Issue by cwouter** [data-forge-notebook/wiki#12]
I can only close the dialog by clicking on the backdrop.

![image](https://user-images.githubusercontent.com/1439383/109062075-bcae6200-76e7-11eb-9da9-ac3e7c4c20ae.png)

**Comment by ashleydavis** [comment]
Will look at it this week! Thanks for reporting it.

**Comment by ashleydavis** [comment]
Sorry been a bit crazy, hoping to look at this soon.

**Comment by ashleydavis** [comment]
This is fixed in version 1.10.5, coming soon.

Thanks so much for reporting the issue.
