### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by odnodn** [data-forge-notebook/wiki#13]
Please urgently supply a dark theme for DFN, otherwise it is pretty hard to work with DFN for a longer period of time without getting eye strain. Dont't want to wait for v2 for it unless you plan to relase v2 anytime soon. Thanks.

**Comment by ashleydavis** [comment]
Hi @odnodn , I hear you and I think it's really important to have a dark theme.

I'm starting the work on V2 right at this moment and I'll be opening it up to the community to help me style the next generation of DFN. If you know CSS you'll be able to work on it yourself!

In the coming weeks I'll be sending emails to my mailing list and updating this wiki to explain and give details on what's coming next for DFN.
