### ISSUE TITLE
Zoom Out button does not work.

### ISSUE THREAD

**Issue by SHoar** [data-forge-notebook/wiki#2]
I've downloaded and tried DFN v1.8.0 for both Windows and Mac - While I can Zoom in ( + ), Any attempt to Zoom Out ( - ) does not work. So far, the only way to reset the Zoom is to close DFN and re-open

**Comment by ashleydavis** [comment]
Thanks Sean! This is fixed now and I'll release DFN 1.8.1 in the next few days.
