### ISSUE TITLE
NoteBookPro data forge typescript didn't compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by SoniaKaudjhis** [data-forge-notebook/wiki#3]
Issue : 
I recently run Noteboo pro **1.93** on my linux **Unbuntu 18.04**. I have an issue when i want to evaluate my code in type script 
Here is the error message that I have :
![Screenshot from 2020-07-12 10-29-18](https://user-images.githubusercontent.com/1808514/87249039-c7530a00-c42a-11ea-9963-74ba787ccc2a.png)
According the error message _File '/tmp/.mount_Data-FR7Rnoa/ts-build/evaluation-engine/node_modules/typescript/lib/lib.es2015.d.ts' not found._
I checked under the following folder /tmp/.mount_Data-FR7Rnoa/ts-build/evaluation-engine, the folder node_modules is nor created by the application 
![Screenshot from 2020-07-12 10-34-45](https://user-images.githubusercontent.com/1808514/87249196-98896380-c42b-11ea-9e62-74183cb12167.png)

**Comment by ashleydavis** [comment]
Thanks for logging the issue! I'm already working on a fix to this. Hope to get a new release out this week.

**Comment by ashleydavis** [comment]
Hi Sonia, I've fixed the issue with TypeScript notebooks and just about to release version 1.9.4 of Data-Forge Notebook. You should get an email soon.

Please reopen this issue or create a new issue if you have any other problems.

**Comment by SoniaKaudjhis** [comment]
Hi David, I have question about module. I have a module cheerio that use in my script but it didn't load correctly in my project. 
when I mouse over on the module normally it show me where it installed it like this 
![Screenshot from 2020-07-15 15-00-11](https://user-images.githubusercontent.com/1808514/87584824-12c81b00-c6ac-11ea-9940-fa5f614f7bff.png)
but I didn't have the same for my cheerio module : 
![Screenshot from 2020-07-15 15-00-27](https://user-images.githubusercontent.com/1808514/87584935-41de8c80-c6ac-11ea-92ee-1ead3c5b846f.png)
I verified that the module is correctly installed on my computer 
![Screenshot from 2020-07-15 15-04-05](https://user-images.githubusercontent.com/1808514/87585053-75b9b200-c6ac-11ea-8226-8a4536acd1f8.png)
So how the module work properly in Notebook ?

**Comment by ashleydavis** [comment]
I don't understand what the problem is. 

Can you use the module? Do you get any errors?

**Comment by SoniaKaudjhis** [comment]
> I don't understand what the problem is.
> 
> Can you use the module? Do you get any errors?

I use cheerio module 
when I run script I have the following error message : 
![Screenshot from 2020-07-16 18-49-34](https://user-images.githubusercontent.com/1808514/87730212-213e3180-c795-11ea-9f66-6e4e2c9c170a.png)
This is mean the variable cheerio is null because the software could not load the module cheerio. So when it comes to call the function .load. it cannot did that because the variable is null
At the beginning of my code I use the following statement in order to import all the libraries I need. 
![Screenshot from 2020-07-16 18-53-39](https://user-images.githubusercontent.com/1808514/87730593-40898e80-c796-11ea-8879-799bd9cd4a5e.png)
I noticed that Notebook could find all modules except the cheerio module. For example when I mouse-over on the path of data-forge module 
![Screenshot from 2020-07-16 18-59-12](https://user-images.githubusercontent.com/1808514/87730817-dcb39580-c796-11ea-946b-30c599937268.png)
But for cheerio : I have nothing. It doesn't show me the path of module. it seems it cannot load it into the notebook forge
![Screenshot from 2020-07-16 19-07-19](https://user-images.githubusercontent.com/1808514/87731456-8a737400-c798-11ea-9b5f-725e92033773.png)

So I asked how can I import correctly npm modules ?

**Comment by ashleydavis** [comment]
It depends on the module.

Here's some information that shows you how to import Cheerio into TypeScript code: 
https://stackoverflow.com/questions/47144540/import-cheerio-module-to-typescript-app

Please let me know if that helps.

**Comment by ashleydavis** [comment]
The "scraping-demo" example also has an example of using Cheerio, but that's in JavaScript rather than TypeScript.
