### ISSUE TITLE
display.html problem

### ISSUE THREAD

**Issue by telemarket2** [data-forge-notebook/wiki#4]
display.html render does not support utf-8 characters

var data = `
<h1>Helló világ</h1>
<p>'óüöóüáéű'</p>`;
display.html(data);

output:
Hell� vil�g
�������%u0171

**Comment by ashleydavis** [comment]
Thanks for reporting this issue.

I just want to confirm what you expect this to look like:

![image](https://user-images.githubusercontent.com/625126/91004146-bba45700-e616-11ea-8994-0ac8a863d047.png)

Let me know if that's what you expect or something else.

**Comment by telemarket2** [comment]
the exported html is fine too,
but my issue is the following:

![Screenshot 2020-08-24 at 10 29 28](https://user-images.githubusercontent.com/10772613/91022233-29d82200-e5f5-11ea-8794-f3ac6b3b53c3.png)

**Comment by ashleydavis** [comment]
This is fixed now. It will be included in release 1.9.6 which is coming soon.

Output now looks like this:

![image](https://user-images.githubusercontent.com/625126/91125741-c4b02980-e6e5-11ea-9893-5bd9893564e7.png)
