### ISSUE TITLE
JavaScript Evaluation not starting on ChromeOS (Linux Container)

### ISSUE THREAD

**Issue by tokensalad** [data-forge-notebook/wiki#7]
Message: "Evaluation engine is starting, please wait a moment before running your code".

The log shows:
[error] Uncaught exception from editor window 34bbbeee-6faf-4085-b883-dc82db458a8d
[error] Error: Cannot read property 'signatures' of undefined

TypeError: Cannot read property 'signatures' of undefined
    at file:///tmp/.mount_Data-FrXEBHG/resources/app.asar/lib/monaco-editor/min/vs/editor/editor.main.js:1439:311
    at file:///tmp/.mount_Data-FrXEBHG/resources/app.asar/lib/monaco-editor/min/vs/editor/editor.main.js:38:735

**Comment by ashleydavis** [comment]
Just sent you an email, could you please reply to that email and attach your log file. Thanks.

**Comment by ashleydavis** [comment]
You got it working on ChromeOS right?

**Comment by tokensalad** [comment]
No, and I have realised that whilst the previous version does launch via the files method I mentioned earlier, version 1.10.0 does not launch at all: 
![Screenshot 2020-12-02 at 06 02 06 - Display 2](https://user-images.githubusercontent.com/26554724/100834683-3aa1fa80-3464-11eb-92aa-c317f9122a91.png)

**Comment by tokensalad** [comment]
Sorry scratch that. It was my fault. 1.9.5 did not work but 1.10.1 is working fine now. I will spend a bit of time playing around and then will start posting some stuff on it (I'll also do the install instructions).

Gary

**Comment by ashleydavis** [comment]
That's great.  Please feel free to contribute a page to the wiki for installing on Chrome OS!

**Comment by tokensalad** [comment]
Never done it before, but I'm sure I'll figure it out. ;-)

**Comment by tokensalad** [comment]
I think you may need to add me as a contributor in order for me to have access

**Comment by ashleydavis** [comment]
Added you!
